---
# tasks file for mediapeers.s3-website-hosting

- name: Name of the website s3 bucket that will be used
  debug:
    var: s3_website_bucket_name

- name: Create S3 bucket for website hosting
  s3_bucket:
    name: "{{ s3_website_bucket_name }}"
    policy: "{{ lookup('template', 's3_read_website_bucket.json.j2') }}"
    state: present
    region: "{{ s3_website_bucket_region }}"
  register: website_bucket

- name: S3 bucket details
  debug:
    var: website_bucket
    verbosity: 1

- name: Configure S3 bucket for website hosting
  s3_website:
    name: "{{ website_bucket.name }}"
    suffix: "{{ s3_website_root_object }}"
    state: present

- name: Output Website domains
  debug:
    var: s3_website_alias_domain_names

- name: Search CloudFront distribution based on alias domain names given (task fails if cloudfront still needs creating)
  cloudfront_facts:
    distribution: true
    domain_name_alias: "{{ item }}"
  ignore_errors: true
  with_items: "{{ s3_website_alias_domain_names }}"
  register: distribution_search

- name: Make sure role internal facts are set to null in case they have been previously set (to not carry over old values)
  set_fact:
    s3_website_existing_distribution_config: null
    s3_website_found_distribution: null
    s3_website_existing_distribution_id: null

- name: Assign first found element to variable
  set_fact:
    s3_website_found_distribution: "{{ distribution_search.results | selectattr('failed', 'equalto',  false) | list | first }}"
  when: distribution_search.results | selectattr('failed', 'equalto',  false) | list | length > 0

- name: Extract distribution config if Cloudfront distribution was found
  set_fact:
    s3_website_existing_distribution_config: "{{ s3_website_found_distribution.ansible_facts.cloudfront.result.Distribution.DistributionConfig }}"
    s3_website_existing_distribution_id: "{{ s3_website_found_distribution.ansible_facts.cloudfront.result.DistributionId }}"
  when:
    - s3_website_found_distribution is not none
    - s3_website_found_distribution.ansible_facts is defined

- name: Output infos of existing CloudFront distribution (confirm if correct one was matched)
  debug:
    msg: "Distribution-ID: {{ s3_website_existing_distribution_id }} | Aliases (CNAMES): {{ s3_website_existing_distribution_config.Aliases.Items }}"
  when:
    - s3_website_existing_distribution_config is not none

- name: Wait to give time to read above message
  pause:
    seconds: 15
  when:
    - s3_website_existing_distribution_config is not none

- name: Set caller reference to pre-existing one or generate new one for creating new Cloudfront distribution
  set_fact:
    cloudfront_caller_reference: "{{ s3_website_existing_distribution_config.CallerReference | default(generated_cloudfront_caller_reference) }}"

- name: Output caller reference to be used to identify Cloudfront dist
  debug:
    var: cloudfront_caller_reference

# Check all parasms for cloudfront_distribution module here:
# https://docs.ansible.com/ansible/latest/modules/cloudfront_distribution_module.html#parameters
# If s.th. doesn't update as expected see if a purge_xx flag need to be added
- name: Create or update Cloudfront Website distribution
  cloudfront_distribution:
    enabled: true
    origins:
      - id: 'S3-{{ s3_website_bucket_name }}'
        domain_name: '{{ s3_website_bucket_name }}.s3-website-{{ s3_website_bucket_region }}.amazonaws.com'
        custom_origin_config:
          origin_protocol_policy: 'http-only'
          http_port: 80
          https_port: 443
        custom_headers: []
    default_root_object: "{{ s3_website_root_object }}"
    price_class: "{{ s3_website_price_class }}"
    ipv6_enabled: true
    cache_behaviors: []
    default_cache_behavior:
      target_origin_id: 'S3-{{ s3_website_bucket_name }}'
      viewer_protocol_policy: 'redirect-to-https'
      allowed_methods:
        items:
          - HEAD
          - GET
        cached_methods:
          - HEAD
          - GET
      min_ttl: 0
      default_ttl: "{{ s3_website_caching_default_ttl }}"
      max_ttl: "{{ s3_website_caching_max_ttl }}"
      compress: true
      smooth_streaming: false
      forwarded_values:
        query_string: false
        headers: []
        cookies: { forward: 'none' }
        query_string_cache_keys: []
      lambda_function_associations: "{{ s3_website_cloudfront_lambda_functions }}"
      trusted_signers: { enabled: false, items: [] }
    http_version: 'http2'
    custom_error_responses:
      - { error_code: 403, response_page_path: "/{{ s3_website_root_object }}", response_code: '200', error_caching_min_ttl: 300 }
      - { error_code: 404, response_page_path: "/{{ s3_website_root_object }}", response_code: '200', error_caching_min_ttl: 300 }
    aliases: "{{ s3_website_alias_domain_names }}"
    purge_aliases: yes # important, so only specified aliases remain
    viewer_certificate:
      ssl_support_method: 'sni-only'
      minimum_protocol_version: "{{ s3_website_cloudfront_tls_policy }}"
      certificate: "{{ s3_website_certificate_arn }}"
      acm_certificate_arn: "{{ s3_website_certificate_arn }}"
      certificate_source: 'acm'
    comment: 'Created by Ansible s3-website-hosting role'
    caller_reference: "{{ cloudfront_caller_reference }}"
    logging:
      enabled: false
      include_cookies: false
      bucket: ''
      prefix: ''
    state: present
  register: cloudfront_website_distribution

- name: Output result diff
  debug:
    var: cloudfront_website_distribution.diff

- name: Save Cloudfront Domain and ID in variables
  set_fact:
    cloudfront_domain: "{{ cloudfront_website_distribution.domain_name }}"
    cloudfront_id: "{{ cloudfront_website_distribution.id }}"

- name: Output Cloudfront domain
  debug: var=cloudfront_domain

- name: Output Cloudfront ID
  debug: var=cloudfront_id

- name: Create DNS alias for CloudFront distribution on Route53
  route53:
    command: create
    zone: "{{ item.split('.')[-2:] | join('.') }}"
    record: "{{ item }}"
    type: A
    value: "{{ cloudfront_domain }}"
    alias: True
    overwrite: True
    alias_hosted_zone_id: "{{ cloudfront_hosted_zone_id }}"
  with_items: '{{ s3_website_alias_domain_names }}'
  when: s3_website_create_dns_record
